filter {
    # Processing of IP addresses.
    if [hostname] {
        mutate {
            add_field => { "[syslog][name]" => "%{[hostname]}" }
            add_field => { "[syslog][inputname]" => "%{[inputname]}" }
            add_field => { "[syslog][ip]" => "%{[host]}" }
            add_field => { "[ifTable][index]" => "%{[interfaceindex]}" }
            remove_field => [ "hostname","host","inputname","interfaceindex" ]
        }
        mutate{
            add_field => { "[host][ip]" => "%{[FromHost]}" }

       }

    }



    if [iTtable][index]{
        mutate {
            add_field => { "[@metadata][in_if_key_sup]" => "%{[host][ip]}::ifName.%{[ifTable][index]}" }
        }
        translate {
            dictionary_path => "/etc/logstash/dictionaries/ifName.yml"
            source => "[@metadata][in_if_key_sup]"
            target => "[ifTable][ifName]"
            fallback => "index: %{[ifTable][index]}"
            refresh_behaviour => "replace"
        }
        translate {
            dictionary_path => "/etc/logstash/dictionaries/ifNamevlan.yml"
            source => "[@metadata][in_if_key_sup]"
            target => "[ifTable][ifNamevlan]"
            fallback => "index: %{[ifTable][index]}"
            refresh_behaviour => "replace"
        }
        translate {
            dictionary_path => "/etc/logstash/dictionaries/ifSup.yml"
            source => "[@metadata][in_if_key_sup]"
            target => "[ifTable][ifSupervision]"
            fallback => "false"
            refresh_behaviour => "replace"
        }
    }

    if [host][ip] {
        # If localhost then use the IP from the host source.
        if [host][ip] == "127.0.0.1" {
            mutate {
                replace => { "[host][domain]" => "%{[host][ip]}" }
            }
        } else {
            mutate {
                add_field => { "[host][domain]" => "%{[host][ip]}"}
            }
        }

        # Resolve host IP address to hostname.
        if [@metadata][resolve_ip2host] == "true" or [@metadata][resolve_ip2host] == "endpoints" {
            dns {
                reverse => [ "[host][domain]" ]
                action => "replace"
                nameserver => "${LOGSTASH_NAMESERVER}"
                hit_cache_size => "${LOGSTASH_DNS_HIT_CACHE_SIZE}"
                hit_cache_ttl => "${LOGSTASH_DNS_HIT_CACHE_TTL}"
                failed_cache_size => "${LOGSTASH_DNS_FAILED_CACHE_SIZE}"
                failed_cache_ttl => "${LOGSTASH_DNS_FAILED_CACHE_TTL}"
            }
        }

            mmdb {
                  source => "[host][ip]"
                  database => "/etc/logstash/dictionaries/XXXX.mmdb"
                  target => "[host]"
            }
            if [host][longitude] {
              mutate {
                add_field => { "[host][geo][location]" => "%{[host][latitude]},%{[host][longitude]}" }
                add_field => { "[host][geo][tz][name]" => "%{[host][tz]}" }
              }
            }
            if [host][WWW] {
              mutate {
                add_field => { "[WWW]" => "%{[host][WWW]}" }
              }
            }
#         }
    }
}
