# Rsyslog : output plugin
output {
    #stdout
    #{
    #    codec => rubydebug
    #}
    opensearch {
        action => "index"
        #ilm_enabled => false 
        hosts => [ "${O_Node1}", "${O_Node2}", "${O_Node3}", "${O_Node4}" ]
        ssl => "${O_SSL_ENABLE:true}"
        ssl_certificate_verification => "${O_SSL_VERIFY:false}"
        user => "${O_USER}"
        password => "${O_PASSWD}"
#document_type => "_doc"
        index => "rsyslogstach-2.0.1-%{+YYYY.MM.dd}"
    }
}
